### ISSUE TITLE
MESSAGE-MACRO: Macro runs after MESSAGE scenario solves "optimal with unscaled inf."

### ISSUE THREAD

**Issue by OFR-IIASA** [iiasa/message_ix#337]
After CPLEX finishes optimization of a scenario, with a status "optimal with unscaled infeasibilities", which with MESSAGE standalone would return an error (?), MACRO will still run and possibly even "converge". This will return an error after macro completes "successfully".

```
--- MESSAGE-MACRO_run.gms(5072) 631 Mb
--- GDX File c:\repo\message_ix\message_ix\model\output\MsgOutput_ENGAGE_SSP2_v4_EN_NPi2020_1200_step1.gdx
--- MESSAGE-MACRO_run.gms(5080) 631 Mb
+++ End of MESSAGEix-MACRO run - have a nice day! +++
*** Status: Normal completion
--- Job MESSAGE-MACRO_run.gms Stop 04/18/20 09:47:15 elapsed 0:20:53.408
2020-04-18 09:47:15,442 DEBUG at.ac.iiasa.ixmp.database.DbDAO:2041 - loading elements for set 'map_temporal_hierarchy' from database...
2020-04-18 09:47:15,446 DEBUG at.ac.iiasa.ixmp.database.DbDAO:2041 - loading elements for parameter 'duration_time' from database...
2020-04-18 09:47:15,486 DEBUG at.ac.iiasa.ixmp.objects.TimeSeries:109 - Cleaning cache...
2020-04-18 09:47:15,486 DEBUG at.ac.iiasa.ixmp.objects.TimeSeries:109 - Cleaning cache...
--- Warning: The GAMS version [24.9.1] differs from the API version [24.8.3].
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\Scripts\mix-data-script.py", line 11, in <module>
load_entry_point('message-data', 'console_scripts', 'mix-data')()
File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 717, in main
rv = self.invoke(ctx)
File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 555, in invoke
return callback(*args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\click\decorators.py", line 27, in new_func
return f(get_current_context().obj, *args, **kwargs)
File "c:\repo\message_data_clean_test_rep\message_data\projects\engage\__init__.py", line 73, in run
main(context)
File "c:\repo\message_data_clean_test_rep\message_data\projects\engage\runscript_main.py", line 120, in main
low_dem_scen='npi_low_dem_scen')
File "c:\repo\message_data_clean_test_rep\message_data\projects\engage\scenario_runner.py", line 342, in run
self.solve(rep_scen_name, copy_demands=True)
File "c:\repo\message_data_clean_test_rep\message_data\projects\engage\scenario_runner.py", line 247, in solve
var_list=['I', 'C', 'GDP'])
File "c:\repo\message_ix\message_ix\core.py", line 437, in solve
super().solve(model=model, solve_options=solve_options, **kwargs)
File "c:\repo\ixmp\ixmp\core.py", line 1490, in solve
model.run(self)
File "c:\repo\message_ix\message_ix\models.py", line 100, in run
result = super().run(scenario)
File "c:\repo\ixmp\ixmp\model\gams.py", line 154, in run
var_list=as_str_list(self.var_list) or [],
File "c:\repo\ixmp\ixmp\backend\jdbc.py", line 353, in read_file
self.jindex[ts].readSolutionFromGDX(*args)
jpype._jclass.IxException: at.ac.iiasa.ixmp.exceptions.IxException: This Scenario is not checked out - no changes to discard!
2020-04-18 09:47:15,634 INFO at.ac.iiasa.ixmp.Platform:157 - closed the connection to database 'jdbc:oracle:thin:@gp3.iiasa.ac.at:1521:GP3'
```

**Comment by khaeru** [comment]
@behnam-zakeri @volker-krey FYI—this seems to be a consequence of #223, and might possibly be taken up and addressed as part of #327.

The second line gives a clue as to which (model, scenario) combination produced this problem for @OFR-IIASA: ``MsgOutput_ENGAGE_SSP2_v4_EN_NPi2020_1200_step1.gdx``—this may help in trying to reproduce, diagnose, and resolve the issue.

**Comment by OFR-IIASA** [comment]
One solution that has worked in the past was to use the cplex lpmethod 2 and then use the advanced bases. This has worked in the past, but the issue that I encountered now, is that solving the initial scenarios takes +10 hours (I stopped the solving process after 10 hours).

**Comment by khaeru** [comment]
> This doesn't solve the actual problem described in the issue, but has served as a workaround

Right.

Can you clarify what the desired behaviour is here? If MESSAGE solves to optimality with unscaled feasibilities, **should** MACRO run? Or should it stop with an error?

@zikolach is there any reason this should happen?
```
self.jindex[ts].readSolutionFromGDX(*args)
jpype._jclass.IxException: at.ac.iiasa.ixmp.exceptions.IxException: This Scenario is not checked out - no changes to discard!
```

**Comment by OFR-IIASA** [comment]
I believe that a scenario being optimal with unscaled infeasibilities returns an error for message standalone - @danielhuppmann is this true? If this is the case, then I believe that macro shouldnt be run if encountering unscaled infeasibilities, although I can be mistaken, as macro did converge in this case - possibly @volker-krey can also comment on the desired behavior.

**Comment by zikolach** [comment]
@khaeru There should some more information about error to be logged out (see [here](https://github.com/iiasa/ixmp_source/blob/master/src/main/java/at/ac/iiasa/ixmp/objects/Scenario.java#L1598)). But it also seems like an issue in the code - it should probably be `checkOut(false);` instead of `db.setStatus(runId, LOCKED_IN_DB);`

**Comment by OFR-IIASA** [comment]
In discussion with @volker-krey , @behnam-zakeri and @khaeru it was decided that the default behavior in such cases should be, that if MESSAGE is solved optimally with unscaled infeasibilities, then macro should NOT continue.

**Comment by adrivinca** [comment]
suggested solutions, which I have not tested

- using `solve_options={'barcrossalg': '2'}` to avoid unscaled infeasibilities

- adding `scaind=1` in the 'cplex.opt' file, may allow a faster solution. see the [CPLEX documentation](https://www.gams.com/latest/docs/S_CPLEX.html#CPLEXscaind)

**Comment by gidden** [comment]
Quick note - you _should_ be able to invoke `scaid` in the same way via `solve_options`

**Comment by khaeru** [comment]
> you _should_ be able to invoke `scaid` in the same way via `solve_options`

I confirm you can.

Basically I think the issue is here:
https://github.com/iiasa/message_ix/blob/51ccdfb631e815bc4142df45650f908900c9dbf6/message_ix/model/MESSAGE/model_solve.gms#L29-L40

The conditional is not catching whatever attributes of `MESSAGE_LP` reflect this "optimal with unscaled infeasibilities", and so it does not `abort`.

**Comment by OFR-IIASA** [comment]
After playing with some alternatives, I have the following solution to counteract the issue. I have added a few lines to generate a second "cplex.opt" file as "cplex.op2" in "models.py", which is copy of the first with the addition of the argument "barcrossalg = 2". In "MESSAGE-MACRO_run.gms", there is now an if-statement that checks for the solve-status of MESSAGELP. Unscaled infeasibilities have the status 5; upon encountering this, the optfile used by MESSAGELP will be the latter of the two, which includes the barcossalg option.
I have tried other solutions, but cplex parameters cannot be directly edited in a loop, hence the only option I have found is to switch to a second cplex options file. The changes will be added to PR #645 .
