### ISSUE TITLE
anaconda installation ignoring new version (always installing first version)

### ISSUE THREAD

**Issue by DIUANA** [iiasa/message_ix#364]
Hi all

When I try to install message-ix via Anaconda (conda install -c conda-forge message-ix)

It installs the version 1.0.0 of message_ix instead of the latest version 3.0.1

I have tried to install based on message-ix-3.0.1-py_0.tar.bz2 file but it generates a lot of incompatibilities between the version and other dependencies. I tried to install from source but it did not work either (https://github.com/iiasa/ixmp/issues/337)

I have also tried to install the 1.0.0 version and update it manually but it failed as well.

I have tried with different Anaconda versions and I am getting the same outcome.

At last I tried conda install -c conda-forge/label/cf202003 message-ix to install the version 2.0 but this is installing the version 1.0.0 too.

Have anyone faced this issue?
All the Best

**Comment by behnam-zakeri** [comment]
@DIUANA, thanks for reporting this. We have identified this issue and updated the installation notes accrodingly. You can find the relevant information [here](https://docs.messageix.org/en/master/getting_started.html#install-messageix-via-anaconda). Please let us know if this didn't fix your issue.

**Comment by volker-krey** [comment]
It seems the updated instructions also fix another issue, namely that Anaconda still offers Python 3.7 by default, not 3.8 as described in the 3.0.1 installation instructions.

**Comment by volker-krey** [comment]
I tried to follow the updated instructions which seem to work, but `message-ix show-versions` fails due to a type mismatch (see end of traceback output below).

`Traceback (most recent call last):
  File "C:\Users\krey\anaconda3\envs\message\Scripts\message-ix-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\krey\anaconda3\envs\message\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\krey\anaconda3\envs\message\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\krey\anaconda3\envs\message\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\krey\anaconda3\envs\message\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\krey\anaconda3\envs\message\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\krey\anaconda3\envs\message\lib\site-packages\ixmp\cli.py", line 101, in show_versions_cmd
    ixmp.show_versions()
  File "C:\Users\krey\anaconda3\envs\message\lib\site-packages\ixmp\utils.py", line 377, in show_versions
    gl = _git_log(mod)
  File "C:\Users\krey\anaconda3\envs\message\lib\site-packages\ixmp\utils.py", line 343, in _git_log
    cwd = Path(mod.__file__).parent
  File "C:\Users\krey\anaconda3\envs\message\lib\pathlib.py", line 1038, in __new__
    self = cls._from_parts(args, init=False)
  File "C:\Users\krey\anaconda3\envs\message\lib\pathlib.py", line 679, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Users\krey\anaconda3\envs\message\lib\pathlib.py", line 663, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by khaeru** [comment]
> `message-ix show-versions` fails due to a type mismatch

This seems to be distinct from @DIUANA's issue, so let's move to a distinct issue.

**Comment by DIUANA** [comment]
@behnam-zakeri Thanks benham I followed the updated instructions with a small deviation.

`conda config --prepend channels conda-forge`
`conda create --name message python=3.7`
`conda activate message`
`conda install spyder`
`conda install message-ix`

otherwise when anaconda installs spyder it adds python 3.6, at least it happens for me even considering that the defauls python version is 3.7

I am using the latest anaconda version 2020.02

**Comment by khaeru** [comment]
@DIUANA when you say "I followed the updated instructions", does that mean that they worked for you?

If yes, then please close the issue.
