### ISSUE TITLE
Cannot run messageix-config on Windows10 public desktop

### ISSUE THREAD

**Issue by ypwong22** [iiasa/message_ix#41]
I am trying to install message_ix following the Install from Conda steps. Everything was fine until I ran the config model files command, i.e. 

messageix-config --model_path /path/to/model

The following error message is printed: 

Traceback (most recent call last):
  File "C:\Users\wangy\AppData\Local\Continuum\Anaconda2\envs\py36\Scripts\messageix-config-script.py", line 10, in <module>
    sys.exit(config())
  File "C:\Users\wangy\AppData\Local\Continuum\Anaconda2\envs\py36\lib\site-packages\message_ix\cli.py", line 65, in config
    do_config(model_path=args.model_path, overwrite=args.overwrite)
  File "C:\Users\wangy\AppData\Local\Continuum\Anaconda2\envs\py36\lib\site-packages\message_ix\cli.py", line 53, in do_config
    with open(CONFIG_PATH, mode='w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\wangy\\.local\\message_ix\\config.json'

I could not find a .local folder in C:\\Users\\wangy.

**Comment by gidden** [comment]
To the best of my knowledge, we need a 

```
path = os.dirname(CONFIG_PATH)
if not os.path.exists(path):
    os.makedirs(path)
```

Should be a good issue for a new person to tackle.
