### ISSUE TITLE
conda installs non matching versions of message-ix and ixmp

### ISSUE THREAD

**Issue by fwitte** [iiasa/message_ix#637]
#### Code sample or context

With 

- windows 10
- [miniforge3 version 4.12.0-0 (64 bit)](https://github.com/conda-forge/miniforge) -> conda-forge is the default channel

and

```
conda create -n envname python=3.9
conda activate envname
conda install message-ix
```

I do get the following versions

| Name       | Version | Build        | Channel     |
|------------|---------|--------------|-------------|
| python     | 3.9.13   | hcf16a7b_0_cpython | conda-forge |
| ixmp       | 3.5.0   | pyhd8ed1ab_0 | conda-forge |
| message-ix | 3.1.0   | py_0         | conda-forge |

I also tried it with

```
conda create -n envname python=3.8
conda activate envname
conda install message-ix
```

in that case conda installs

| Name       | Version | Build        | Channel     |
|------------|---------|--------------|-------------|
| python     | 3.8.13   | hcf16a7b_0_cpython | conda-forge |
| ixmp       | 3.5.0   | pyhd8ed1ab_0 | conda-forge |
| message-ix | 3.1.0   | py_0         | conda-forge |

#### Expected result

| Name       | Version | Build        | Channel     |
|------------|---------|--------------|-------------|
| ixmp       | 3.5.0   |  | conda-forge |
| message-ix | 3.5.0   |  | conda-forge |

in both cases, I guess.

Also,

```
message-ix show-version
```

gives me the following error:

```
Traceback (most recent call last):
  File "C:\Users\witt_fa\AppData\Local\miniforge3\envs\message-ix-env38\Scripts\message-ix-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\witt_fa\AppData\Local\miniforge3\envs\message-ix-env38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\witt_fa\AppData\Local\miniforge3\envs\message-ix-env38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\witt_fa\AppData\Local\miniforge3\envs\message-ix-env38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\witt_fa\AppData\Local\miniforge3\envs\message-ix-env38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\witt_fa\AppData\Local\miniforge3\envs\message-ix-env38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\witt_fa\AppData\Local\miniforge3\envs\message-ix-env38\lib\site-packages\ixmp\cli.py", line 111, in show_versions_cmd
    ixmp.show_versions()
  File "C:\Users\witt_fa\AppData\Local\miniforge3\envs\message-ix-env38\lib\site-packages\ixmp\utils.py", line 563, in show_versions
    info.append(("… JVM path", mod.getDefaultJVMPath()))
  File "C:\Users\witt_fa\AppData\Local\miniforge3\envs\message-ix-env38\lib\site-packages\jpype\_jvmfinder.py", line 74, in getDefaultJVMPath
    return finder.get_jvm_path()
  File "C:\Users\witt_fa\AppData\Local\miniforge3\envs\message-ix-env38\lib\site-packages\jpype\_jvmfinder.py", line 212, in get_jvm_path
    raise JVMNotFoundException("No JVM shared library file ({0}) "
jpype._jvmfinder.JVMNotFoundException: No JVM shared library file (jvm.dll) found. Try setting up the JAVA_HOME environment variable properly. 
```

Cheers

**Comment by khaeru** [comment]
Thanks!

Can you try:
```
conda install message-ix==3.5
```
and report the outcome?

**Comment by fwitte** [comment]
Works now, thanks. Kind of strange, that conda does not find the most recent version automatically. The environment solving on the installation also takes a lot more time than it should btw..

Anyway, thank you so far, have a nice day!
